Repository kiva/ui, pull requests merged in 2025-07, with the labels that each got.

#6125 feat: mp-1744 / add huge lending amounts to LBC page
  src/components/BorrowerProfile/BorrowerSideSheetContent.vue
  src/composables/useBorrowerProfileData.js
  src/graphql/query/borrowerProfileSideSheet.graphql
Labels: enhancement

#6150 fix: mp-1753 / Refactorization of BorrowerCarousel & LoanCards component to leverage BP mixin and SideSheet properly
  src/components/BorrowerProfile/BorrowerCountry.vue
  src/components/BorrowerProfile/BorrowerSideSheetContent.vue
  src/components/BorrowerProfile/BorrowerSideSheetWrapper.vue
  src/components/BorrowerProfile/CommentsAndWhySpecial.vue
  src/components/BorrowerProfile/SideSheetLoanHowMoneyHelps.vue
  src/components/MyKiva/BorrowerCarousel.vue
  src/components/MyKiva/BorrowerStatusCard.vue
  src/pages/MyKiva/MyKivaPageContent.vue
  src/pages/Portfolio/ImpactDashboard/LoanCards.vue
  src/pages/Portfolio/ImpactDashboard/LoanCommentModal.vue
  src/plugins/borrower-profile-exp-mixin.js
Labels: bug, enhancement

#6161 fix: mp-1753 – Create Watch for disableCache prop in BorrowerCarousel
  src/components/BorrowerProfile/CommentsAndWhySpecial.vue
Labels: bug

#6157 feat: [MP-1655] | hide atb modal if user has balance #2165
  src/components/WwwFrame/Header/KvAtbModalContainer.vue
  src/graphql/query/userAtbModal.graphql
Labels: enhancement

#6169 feat: mp-1748 – Add Recommendations for Next Regions to Lend To
  src/assets/images/my-kiva/Africa.png
  src/assets/images/my-kiva/Asia.png
  src/assets/images/my-kiva/Central America.png
  src/assets/images/my-kiva/Eastern Europe.png
  src/assets/images/my-kiva/Middle East.png
  src/assets/images/my-kiva/North America.png
  src/assets/images/my-kiva/Oceania.png
  src/assets/images/my-kiva/South America.png
  src/components/MyKiva/LendingStats.vue
  src/pages/MyKiva/MyKivaPage.vue
  src/pages/MyKiva/MyKivaPageContent.vue
Labels: enhancement
